### ISSUE TITLE
Rustup on benchmarksgame?

### ISSUE THREAD

**Issue by llogiq** [TeXitoi/benchmarksgame-rs#10]
@TeXitoi since you manage the Rust entries to the benchmarksgame, what do we need to do to get them to use the next stable version (noting that 1.3.0 is out)?

**Comment by TeXitoi** [comment]
Just waiting that the benchmarksgame maintainer upgrade the rust version. He did that quickly the other times.

**Comment by llogiq** [comment]
He did it. :smile:
