### ISSUE TITLE
New fasta_redux (based on Veedrac's fasta)

### ISSUE THREAD

**Issue by llogiq** [TeXitoi/benchmarksgame-rs#16]
I have a [gist here](https://gist.github.com/llogiq/7e36d840e1144076c2f1) It runs roughly 5 times as fast as my previous attempt (on my machine).

I'll obviously submit it to Rust first before putting a PR here.

If you want to build it, you need to add

```
NUM_CPUS ?= num_cpus-0.2.6

bin/fasta_redux: src/fasta_redux.rs lib/$(NUM_CPUS).pkg
```

to the Makefile.

**Comment by llogiq** [comment]
I have a [rust PR](https://github.com/rust-lang/rust/pull/28623) with both fasta and fasta-redux (sans the num_cpus dependency, stubbornly using 4 threads instead).

**Comment by llogiq** [comment]
Now this issue is only waiting on @TeXitoi to submit the new fasta-redux to the benchmarksgame tracker.

**Comment by TeXitoi** [comment]
https://alioth.debian.org/tracker/index.php?func=detail&aid=315193&group_id=100815&atid=413122
