### ISSUE TITLE
Makefile not portable

### ISSUE THREAD

**Issue by llogiq** [TeXitoi/benchmarksgame-rs#18]
I must've accidentally used some kind of extension when writing the dependency trick, but a friend who runs fedora tells me it fails for him.

I probably should remove the `\n`s and resort to plain `echo`s for maximum portability.

**Comment by TeXitoi** [comment]
My makefile rules depend on gnu make extentions. Thus if on fedora gnu make is not used by default, gmake must be used. Else, thanks to fix it, but no hurry :)
