### ISSUE TITLE
Pull the auto-vectorization trick on n_body?

### ISSUE THREAD

**Issue by llogiq** [TeXitoi/benchmarksgame-rs#25]
The fastest C++ entry calculates the distance by:

``` C++
dsquared = dx[0] * dx[0] + dx[1] * dx[1] + dx[2] * dx[2];
distance = _mm_cvtps_pd(_mm_rsqrt_ps(_mm_cvtpd_ps(dsquared)));
```

Now we cannot use SIMD intrinsics yet, because they're unstable, but perhaps we can have LLVM autovectorize the calculation?

**Comment by TeXitoi** [comment]
Yeah, you can even work on a simd version for the official repo, and then trying to make a version that autovectorize. n-body is, if I remember well, the only benchmark that can use simd, but don't in the official repo.

**Comment by llogiq** [comment]
LLVM apparently isn't clever enough to vectorize `1 / f.sqrt()`, so we'll have to go full SIMD to pull this off.

**Comment by TeXitoi** [comment]
:-( thanks for trying.

**Comment by llogiq** [comment]
My pleasure. Maybe if we had an invsqrt function (that could be annotated internally), LLVM would have an easier time. Then again, SIMD intrinsics are probably usable long before such a function becomes stable.

**Comment by Veedrac** [comment]
The problem, of course, is that Rust has no `-ffast-math` flag, so LLVM cares a lot about correctness of optimizations. We'd be more likely to get `_mm_sqrt_ps` and `_mm_div_ps` separately than the approximate inverses.

**Comment by llogiq** [comment]
Exactly. Even so, a few months hence we'll have stable SIMD, and then we can get rid of all that autovectorization shenanigans.
