### ISSUE TITLE
contribute with fixed num cpus

### ISSUE THREAD

**Issue by tafia** [TeXitoi/benchmarksgame-rs#29]
It is really sad that these code cannot be published because of num_cpus in particular.
We could force it to 4 or 1 ... and add a message stating that the proper way is to use num_cpu crate

**Comment by TeXitoi** [comment]
Which codes? Actually we can use some idiomatic crates as we do with regex. num_cpu can be added.

**Comment by llogiq** [comment]
@tafia do you mean at rust-lang/rust (true, they aren't keen on additional test dependencies)? Or at the benchmarksgame site?

**Comment by tafia** [comment]
Sorry, I meant at the benchmarksgame site. 
Even if these benchmarks do not necessarily represent the reality, this is the first thing people look at when hearing about rust performance. Some tests are 3 times faster in this repo than on the website.

**Comment by llogiq** [comment]
But why would using `num_cpus` stop us from publishing? Using it is perfectly normal Rust, and it's no problem using other crates either.

Apart from that, we may be able to get the number of cpus from `/proc` instead (but that only works on linux)

**Comment by tafia** [comment]
I don't really know. I assumed the site could not use download dependencies and this is what prevented it from using what's been done here. I am probably wrong

**Comment by llogiq** [comment]
We should probably just ask Isaac before speculating.

**Comment by tafia** [comment]
Indeed

**Comment by TeXitoi** [comment]
I just think that it's because the install script does not works. We should just update the instructions to "manually" install external crates. That was working before.

**Comment by llogiq** [comment]
In that case, let's do this – and do it fast, so they can be published. It's high time people see how fast Rust actually is.

**Comment by TeXitoi** [comment]
num_cpu is used in a benchmark.
