### ISSUE TITLE
regex-dna with &[u8] matching

### ISSUE THREAD

**Issue by llogiq** [TeXitoi/benchmarksgame-rs#31]
I have a [gist](https://gist.github.com/llogiq/67fa854d5d5f8afd7f079f2a441e7219) where I use `regex::bytes` instead of plain `regex`. I'd have thought that it should be faster (because we can get rid of the UTF-8 check), but in fact it is _slower_. @BurntSushi there's probably some reason for that, just a heads-up; if the bytes variant should get faster we can retry the measurements.

On my system:

| variant | wall | user | sys |
| --- | --- | --- | --- |
| UTF-8 | 1.52 | 3.94 | 0.33 |
| bytes | 2.23 | 4.50 | 0.35 |

**Comment by BurntSushi** [comment]
Yeah, I noticed this a few weeks ago and though it was curious. I actually can't think of any obvious reason why it's slower. My (more extensive) benchmark suite says `Regex::new` and `bytes::Regex::new` have comparable performance. I'll look into it.

Another thing you could try is `from_utf8_unchecked`.

**Comment by BurntSushi** [comment]
Ahahahahaha. This is because `replace_all` in `Regex` uses `push_str`, which should be a `memcpy`. On the other hand, `bytes::Regex` uses `extend`, which seems to be slower, and therefore I'm guessing doesn't get optimized down to a `memcpy`. Nice.

**Comment by BurntSushi** [comment]
OK, once I fixed that in `regex`, the best of 3 for `bytes::Regex` was `0.59s` and for `Regex` it was `0.61s`. I figured it would be that small. It's barely perceptible and probably in the noise because I not-so-infrequently see both of them get up to `0.7s`.

**Comment by llogiq** [comment]
Ok then I'm going to wait for a new Regex release so I can submit it without complicating our makefile. Thanks @BurntSushi!
