### ISSUE TITLE
Use std::collections::HashMap in k-nucleotide

### ISSUE THREAD

**Issue by llogiq** [TeXitoi/benchmarksgame-rs#34]
k-nucleotice will probably need to use a std::collections::HashMap, as custom hashmaps are now forbidden and will be replaced (see https://alioth.debian.org/forum/forum.php?thread_id=14969&forum_id=2965&group_id=100815). However, this doesn't preclude us from using a custom Hasher.

cc @Veedrac

**Comment by Veedrac** [comment]
Rust's `HashMap` is _really_ pathological with bad hashers. I've experimented and I don't see any obvious ways to do better than merely using a custom `Hash` (with the default `SipHasher`).

This probably means Rust isn't going to be leading the benchmarks. I quickly threw something together on top of my deprecated pull request and it came out about 3-4x the time in some really bad benchmarks, and those are probably optimistic numbers. It was basically this change:

```
impl Hash for SubSequence {
    fn hash<H: Hasher>(&self, state: &mut H) {
        state.write_u64(self.0);
    }
}
```

along with moving to `std::collections::HashMap<SubSequence, usize>`.

I dunno if there are any smarter ways of doing this.

**Comment by llogiq** [comment]
Why not use a better hasher? The hashmap likely uses the lowest bits. Either shift only by one bit and xor the nucleotide values or use something like `self.0 ^ (self.0 >> 13)` as a hash value, perhaps both.

**Comment by Veedrac** [comment]
Not sure what you mean by "a better hasher". Remember that there are two things in play: the `Hasher` and the `Hash` implementation.

The `state.write_u64(self.0);` just passes the compressed subsequence to the `Hasher` implementation. `SipHasher` is sufficient to get a good hash value from this; something like your example inside a custom `Hasher` struct is not nearly sufficient.

Doing `state.write_u64(self.0 ^ (self.0 >> 13));` inside `Hash` is pointless if we're using `SipHasher`, and if we're using something like an `IdentityHasher` it would merely be a strange place to put the code.

**Comment by Manishearth** [comment]
Is there any reason why Go is faster than rust on this bench? http://benchmarksgame.alioth.debian.org/u64q/performance.php?test=knucleotide

I see why C is fast -- they use a naive hash function -- but Go uses the regular in built map.

Is  this due to the stdlib hashmap?

**Comment by TeXitoi** [comment]
First, this is not my code.

You can see that the cpu time is almost the same for go and rust. Looking at the code, I suspect that's because go schedule the jobs in num cpu routine, when rust just spawn a thread by search. Using a thread pool in the rust implementation (or naively grouping the jobs in 4 threads by hand) should give similar performance to the go implementation.
