### ISSUE TITLE
n-body performance degradation from 1.7 to 1.8

### ISSUE THREAD

**Issue by llogiq** [TeXitoi/benchmarksgame-rs#35]
Isaac [noted](https://users.rust-lang.org/t/why-is-rust-n-body-benchmark-slower-than-c/5951/2) this on a rust-users' thread.

> 14.600s rustc 1.7.0
> 24.533s rustc 1.8.0 

Someone should look into this.

**Comment by TeXitoi** [comment]
It must be llvm that doesn't auto simd the code.

**Comment by crumblingstatue** [comment]
Isn't it possible it regressed because of https://github.com/rust-lang/rust/pull/31545?

**Comment by TeXitoi** [comment]
I don't think do, but that's a possibility.

**Comment by mati865** [comment]
Guess this issue doesn't matter anymore after https://github.com/TeXitoi/benchmarksgame-rs/pull/70?

**Comment by TeXitoi** [comment]
Yep, thanks for the reminder.
