### ISSUE TITLE
Make fannkuch-redux faster using unsafe code

### ISSUE THREAD

**Issue by llogiq** [TeXitoi/benchmarksgame-rs#4]
Knowing that the current version of fannkuch-redux uses a loop to rotate the slice (heh, good pun), I created a small microbenchmark using std::intrinsics::copy instead. Results on my machine:

```
test bench_rotate_16     ... bench:         797 ns/iter (+/- 4)
test bench_rotate_16_new ... bench:          66 ns/iter (+/- 1)
```

The new rotate code:

``` rust
fn rotate_new(x: &mut [i32]) {
    let tmp = x[0];
    let last = x.len() - 1;
    if last <= 0 { return; }
    unsafe { copy(&x[1], &mut x[0], last); }
    x[last] = tmp;
}
```

Tested on nightly, but I think it _should_ work with beta, too. Should we include this?

**Comment by llogiq** [comment]
Used a more current nightly, the results were reversed. I'll close this for now.

**Comment by TeXitoi** [comment]
Even if that's not working, thanks for the contribution.
