### ISSUE TITLE
Why no fasta-redux?

### ISSUE THREAD

**Issue by llogiq** [TeXitoi/benchmarksgame-rs#5]
I noticed that there is no fasta-redux implementation, though the Rust distribution has one. Is there a reason for that?

**Comment by TeXitoi** [comment]
I think the fasta-redux of the rust distribution does not pass the tests. And I don't understand the difference between fasta and fasta-redux, thus I did not take the time to investiguate on this benchmark.

I'll be happy to accept a PR with a fasta-redux implementation :)

**Comment by llogiq** [comment]
The difference is that the redux version should build a lookup table from which the amino acid should be queried. I have taken the "original" Rust version and changed it so that the output matches the requirements (and also the algorithm should, to the best of my knowledge).

I'll try and make a PR to rust-lang/rust first. Should they add it, feel free to grab it from there, otherwise I'll gladly make a PR here.

**Comment by llogiq** [comment]
The [PR](https://github.com/rust-lang/rust/pull/27636) has been accepted and now waits for the next rollup. @TeXitoi Do you want to pull from there or should I add a PR here, too?

**Comment by TeXitoi** [comment]
You can open a PR here. Don't forget to change the header. The last contributor is the one that will submit the benchmark. So put me at the end and I'll submit the bench, or put yourself last but then you'll need to submit it yourself.

**Comment by llogiq** [comment]
PR #6 opened. I'm closing this issue.
