### ISSUE TITLE
Mandelbrot performance regression

### ISSUE THREAD

**Issue by cristicbz** [TeXitoi/benchmarksgame-rs#50]
So weirdly it looks like when ioguy evaluated the mandelbrot solution from #40, preformance degraded by half. I can't reproduce this locally, for me it's always faster, but maybe it's worth reverting the code? https://alioth.debian.org/tracker/?func=detail&atid=413122&aid=315634&group_id=100815

**Comment by TeXitoi** [comment]
Maybe that's LTO related?

**Comment by cristicbz** [comment]
Ah yes, locally LTO makes a big difference for this benchmark!

**Comment by TeXitoi** [comment]
Maybe we can ask Isaac to reuse LTO, the problems may be fixed now. That make me confident for the other benchmarks :smile:

**Comment by cristicbz** [comment]
Check out #52, the other benchmarks seem unaffected by this, it was just to do with inlining stuff.

**Comment by TeXitoi** [comment]
Great!
