### ISSUE TITLE
refactor

### ISSUE THREAD

**Issue by gnzlbg** [TeXitoi/benchmarksgame-rs#66]
As part of `lolbench` (rustc's run-time performance tracking) it might be better to refactor this crate into one crate per benchmark that use the normal `Cargo.toml` to fetch dependencies. This would allow each of the benchmarks to have their own `bench`es, and make it more clear how to run them.

**Comment by llogiq** [comment]
This is not how the benchmarksgame works, alas. Their requirement is one source file per benchmark plus one Makefile to build the benchmarks.

**Comment by gnzlbg** [comment]
@llogiq we can make a workspace, with each benchmark crate being a member of the workspace. We can then add a root crate that checks that the benchmarks only have a single `lib.rs`, and generates a directory ready to export to the benchmarks game. 

Either by parsing the `Cargo.toml`s and generating the `Makefile`, or by checking that a manually written `Makefile` is in sync with the `Cargo.toml`s.

**Comment by TeXitoi** [comment]
https://salsa.debian.org/benchmarksgame-team/benchmarksgame/issues/40

**Comment by gnzlbg** [comment]
Thanks. FWIW, the `rust-lang-rust/packed_simd` crate contains some of the benchmark game examples implemented using rayon+portable simd as "independent crates" (nbody, fannkuch-redux, mandelbrot, and I think that's it). Porting them to rayon+stable SIMD (x86 intel intrinsics) shouldn't be very hard; if somebody wants to do this, it could be done there and set as the "default" run mode for the benchmarks, that way one can compare the performance of the portable SIMD intrinsics vs the architecture specific ones.

**Comment by gnzlbg** [comment]
@TeXitoi you can also argue that one advantage of Rust is how easy the build system and benchmarks are to use, but that due to how the benchmarks must be submitted, none of these features can be used while developing the benchmarks.

**Comment by TeXitoi** [comment]
Isaac doesn't want to change something that is working for him.

**Comment by gnzlbg** [comment]
@TeXitoi how did you read that from its response ? I mean, it appears to me that isaac is open to reevaluating the workflow, but it doesn't want to change it to something that's painful to him which is fair. We should try to find a solution that works for everybody. I think that Rust without cargo is not Rust.

**Comment by TeXitoi** [comment]
I already tried some years ago. I don't have the time to argument on this topic. In practice, the audience don't really care as they don't look at the build process.

I'd really prefer to use cargo, thus, if you have the motivation, I let you argument. I will agree if needed.
