### ISSUE TITLE
spectral-norm fails to build on stable 1.2

### ISSUE THREAD

**Issue by llogiq** [TeXitoi/benchmarksgame-rs#8]
The `AdditiveIterator` use can simply be removed, however, `os::num_cpus()` needs to be replaced (can use any of the cpuinfo crates), as well as the `core_simd` types (can use Huon Wilson's [simdty](https://crates.io/crates/simdty)).

I also note that even beta 1.3 disallows `#![feature(..)]` flags (as of now, tested on the playground).

**Comment by TeXitoi** [comment]
There is a working version on spectral norm in tree, but llvm don't autovectorise it. A pseudo vectoriser version of fn A should do the trick but I don't have the time to investigate.

Core simd need the feature simd last time I checked so it can't be used I'm stable.

**Comment by llogiq** [comment]
I meant the simd crate, not `core::simd`.

**Comment by TeXitoi** [comment]
the simd crate doesn't work on stable, it need features.

The quite working workaround that I've used is to locally declare struct compatible with the simd objects and then rely on llvm to autovectorise the thing. But as it is not forced, the `fn A()` is not autovectorized, and then simd are not used (as it can be seen in the generated ASM).  I think writing something like `fn A(i: u64x2, j: u64x2) -> f64x2` and use it where we use `A()` should do the trick, but I didn't take the time to try.

See https://github.com/TeXitoi/benchmarksgame-rs/blob/master/src/spectralnorm.rs

**Comment by TeXitoi** [comment]
https://alioth.debian.org/tracker/index.php?func=detail&aid=315140&group_id=100815&atid=413122

**Comment by llogiq** [comment]
Should I close this or leave it open until either rustc vectorizes it or a SIMD version lands?

**Comment by TeXitoi** [comment]
We can close it when it is accepted by the official site.

**Comment by TeXitoi** [comment]
#9 opened to track the hypothetical SIMD future version.
