### ISSUE TITLE
Improve spectralnorm

### ISSUE THREAD

**Issue by TeXitoi** [TeXitoi/benchmarksgame-rs#9]
The `fn A()` is not autovectorized, and then simd are not used anywhere (as it can be seen in the generated ASM). I think writing something like `fn Ax2(i: u64x2, j: u64x2) -> f64x2` and use it where we use `A()` should do the trick.

**Comment by llogiq** [comment]
Could we use the simd crate? It's not tested on stable AFAIK, but it might work on beta, at least.

**Comment by TeXitoi** [comment]
The simd crate is used on the rust repo. You can contribute here, but it'll be merged here when stable will support simd (or a couple of days before).

This issue is about writing the code such that llvm optimizes with simd without using the simd crate.

**Comment by llogiq** [comment]
Ah, I see. Do you mean something like the following?

```
#[allow(non_camel_case_types)]
#[derive(Debug)]
struct u64x2(u64, u64);
impl std::ops::Add for u64x2 {
    type Output = Self;
    fn add(self, rhs: Self) -> Self {
        u64x2(self.0 + rhs.0, self.1 + rhs.1)
    }
}
impl std::ops::Div for u64x2 {
    type Output = Self;
    fn div(self, rhs: Self) -> Self {
        u64x2(self.0 / rhs.0, self.1 / rhs.1)
    }
}

fn Ax2(i: u64x2, j: u64x2) -> f64x2 {
    f64x2(((i.0 + j.0) * (i.0 + j.0 + 1) / 2 + i.0 + 1) as f64,
           ((i.1 + j.1) * (i.1 + j.1 + 1) / 2 + i.1 + 1) as f64)
}
```

I don't see any advantage to that in a [minimal test setup](http://is.gd/AV0FVa) (look at the assembly output). Maybe within a loop?

**Comment by llogiq** [comment]
Also if I try to keep the operations within x2 representations, the assembly stays the same: http://is.gd/65q7NN

**Comment by TeXitoi** [comment]
It seems different in release mode.

**Comment by TeXitoi** [comment]
And yes, I was thinking of 

``` rust
fn ax2(i: u64x2, j: u64x2) -> f64x2 {
    ((i + j) * (i + j + u64x2(1, 1)) / u64x2(2, 2) + i + u64x2(1, 1)).into()
```

**Comment by llogiq** [comment]
Yeah, I just diffed the assembly versions. They _are_ different, although I'm not sure if the vectorized version is actually faster. Guess there's only one way to find out... :smile:
